### ISSUE TITLE
cannot load released ckpt to perform inference

### ISSUE THREAD

**Issue by wanglixilinx** [isl-org/lang-seg#2]
Hi, @Boyiliee ,
    Great work. I just follow your instruction to run the demo and failed. The issue occurred when loading the model from the released checkpoint. I attach the errors below:
"super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: [enforce fail at inline_container.cc:145] . PytorchStreamReader failed reading zip archive: invalid header or archive is corrupted"

looking forward to your feedback.

**Comment by Boyiliee** [comment]
Hi @wanglixilinx, thanks for your question and interest in LSeg! 

It works well for me, maybe can you try downloading again to see if it solves the problem? I guess it might be because there were some bugs that you might download part of the file?

Please let me know if you have any further questions!

Best,
Boyi
