### ISSUE TITLE
question about the "other" class

### ISSUE THREAD

**Issue by Dingry** [isl-org/lang-seg#30]
Hi, thanks for your great work.
I noticed that you use "other" class to refer background or unknown classes in training. May I ask where is the corresponding processing code? Beside, do you encode the unseen (novel) classes as "other" in training procedures?

**Comment by Boyiliee** [comment]
Hi @Dingry,

Thanks for your interest in LSeg!

This is a great question and we are a little surprised that we didn't do any processing on the dataset. If the dataset contains 'other', then we will use it. Otherwise, we directly use the label provided in the selected dataset. No additional processing procedure is required.

Hope this helps.

Best,
Boyi
